"""Local capability-token auth for the desktop backend.

This is not user login.  It only proves that a caller received the
per-process token generated by the Tauri launcher for this backend instance.
"""

from __future__ import annotations

import hmac
import os
import re

BACKEND_AUTH_TOKEN_ENV = "BACKEND_AUTH_TOKEN"
WEBSOCKET_AUTH_PROTOCOL_PREFIX = "auth."

_ALLOWED_ORIGINS = {
    "tauri://localhost",
    "http://tauri.localhost",
    "https://tauri.localhost",
}
_LOCAL_HTTP_ORIGIN_RE = re.compile(r"^https?://(localhost|127\.0\.0\.1)(:\d+)?$")


def get_backend_auth_token() -> str | None:
    """Return the configured backend capability token, if auth is enabled."""
    token = os.getenv(BACKEND_AUTH_TOKEN_ENV)
    return token or None


def is_origin_allowed(origin: str | None) -> bool:
    """Allow Tauri origins and local development origins; non-browser clients may omit Origin."""
    if origin is None:
        return True
    return origin in _ALLOWED_ORIGINS or _LOCAL_HTTP_ORIGIN_RE.fullmatch(origin) is not None


def is_bearer_token_authorized(authorization: str | None, expected_token: str) -> bool:
    """Validate an HTTP ``Authorization: Bearer <token>`` header."""
    if authorization is None:
        return False
    prefix = "Bearer "
    if not authorization.startswith(prefix):
        return False
    supplied = authorization[len(prefix) :]
    return hmac.compare_digest(supplied, expected_token)


def find_authorized_websocket_subprotocol(header_value: str | None, expected_token: str) -> str | None:
    """Return the matching WebSocket subprotocol carrying the token, if present."""
    if header_value is None:
        return None
    expected = f"{WEBSOCKET_AUTH_PROTOCOL_PREFIX}{expected_token}"
    for raw_protocol in header_value.split(","):
        protocol = raw_protocol.strip()
        if hmac.compare_digest(protocol, expected):
            return protocol
    return None
