"""Generate prototype notices with the repository's existing license auditor."""

import argparse
import importlib.util
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = importlib.util.spec_from_file_location(
        "license_auditor", ROOT / "scripts/third-party-licenses.py"
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("license auditor not found")
    auditor = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = auditor
    spec.loader.exec_module(auditor)
    policy = json.loads((ROOT / "licenses/policy.json").read_text(encoding="utf-8"))
    policy["provisioned_artifacts"] = [
        artifact
        for artifact in policy["provisioned_artifacts"]
        if artifact["name"] == "silero-vad-int8-onnx"
    ]
    # Both local crates belong to this AGPL project; audit the third-party crates.
    packages = [
        package
        for package in auditor.cargo_packages(HERE, features=["reazonspeech"])
        if package.name != "meeting-audio-core"
    ]
    packages += auditor.provisioned_packages(policy)
    auditor.recover_pinned_repository_documents(packages, policy)
    errors = auditor.audit(packages, policy)
    if errors:
        raise RuntimeError("\n".join(errors))
    generated = auditor.render(packages)
    generated = generated.replace(
        "Python packages are resolved from python/uv.lock with `uv sync --locked --no-dev`.",
        "Scope: Rust backend crates (including the ReazonSpeech feature) and embedded Silero.\n"
        "Native sherpa-onnx/ONNX Runtime and ReazonSpeech model files are externally supplied;\n"
        "their licenses and third-party notices must accompany any distribution of those artifacts.",
    ).replace(
        "This file is generated by scripts/third-party-licenses.py. Do not edit manually.",
        "Generated by test/rust-native-backend/generate_notices.py using scripts/third-party-licenses.py.",
    )
    output = HERE / "THIRD-PARTY-NOTICES.txt"
    if args.check:
        if output.read_text(encoding="utf-8") != generated:
            raise RuntimeError("prototype notices are out of date")
    else:
        output.write_text(generated, encoding="utf-8")
    print(f"Prototype license audit passed ({len(packages)} components).")


if __name__ == "__main__":
    main()
